services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - test-backend-volume:/app/backend/database
volumes:
  test-backend-volume:

  sadasfddfdsgagfasbnnayrawgh